version: '3'
services:
  mongosource:
    build:
      context: volumes/mongosource/.
    expose: ["27017"]
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - ./volumes/mongosource/data:/home/data
      - ./volumes/mongosource/bin:/home/bin
    entrypoint: [ "/home/bin/start_mongo_replicaset.sh" ]

  mongoconnector:
    build:
      context: volumes/mongoconnector/.
    volumes:
      - ./volumes/mongoconnector/bin:/home/bin
      - ./volumes/mongoconnector/conf:/home/conf
      - ./volumes/mongoconnector/data:/home/data
    entrypoint: [ "/home/bin/entrypoint.sh" ]
    depends_on:
      - mongosource
      - postgres
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}

  postgres:
    image: postgres:10.0
    expose: ["5432"]
    ports:
      - "5432:5432"
    volumes:
        - ./volumes/postgres/data:/var/lib/postgresql/data

  superset:
    build:
      context: volumes/superset/.
    depends_on:
      - redis
      - postgres
    ports:
      - "8088:8088"
    volumes:
       - ./volumes/superset/bin:/etc/superset/bin
       - ./volumes/superset/conf:/etc/superset/conf
       - ./volumes/superset/data:/etc/superset/data
       - ./volumes/superset/dashboards:/etc/superset/dashboards
    working_dir: /etc/superset/conf
    environment:
      SUPERSET_HOME: /etc/superset/conf
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      SUPERSET_ADMIN_PASSWD: ${SUPERSET_ADMIN_PASSWD}
      SUPERSET_HOME: /etc/superset
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}

  redis:
    image: redis:4.0
    volumes:
      - ./volumes/redis/data:/data

  schemacrawler:
    image: sualeh/schemacrawler
    volumes:
      - ./volumes/schemacrawler/bin:/schemacrawler/bin
      - ./volumes/schemacrawler/data:/schemacrawler/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    entrypoint: [ "/schemacrawler/bin/extract_sql_schema.sh" ]

